import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/header/header";
import SideCard from "@/components/side-card/side-card";
import TrendingCoins from "@/components/trending-coins/trending-coins";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-[#EFF2F5] antialiased overflow-x-hidden scroll-smooth", inter.className)}>
        <Header />
        <div className="py-4 px-2 max-w-[1368px] mx-auto flex w-full gap-4">
          <div className="flex-1 md:flex-[7]">{children}</div>
          <div className="hidden md:flex flex-[3] flex-col gap-4 py-9">
            <SideCard />
            <TrendingCoins />
          </div>
        </div>
      </body>
    </html>
  );
}
